import type { TutorialDefinition } from "./tutorialTypes";

/**
 * Data-driven tutorial registry. Adding a new mechanic later means adding a new entry here —
 * the engine (TutorialOverlay + the detection hook in PuzzleGame) never needs to change.
 *
 * Mini-grid cell types match the real game's legend (see src/data/levels.ts header comment):
 * 0 floor, 2 stone, 3 cave/goal, 5 void, 6 breakable rock, 8 arrow-right, 13 omni arrow,
 * 14 red key, 16 red lock, 18 start marker, 19 teleport, 20 bonus time.
 */
export const TUTORIAL_DEFINITIONS: TutorialDefinition[] = [
  {
    id: "basics",
    title: "Getting Started",
    text: "Walk across the floor to the ladder. Swipe or use arrow keys to move — stone blocks the way.",
    triggerCellTypes: [0, 2, 3],
    miniGrid: [
      [2, 2, 2, 2, 2, 2],
      [2, 18, 0, 0, 0, 3],
      [2, 2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 2, y: 1 }, { x: 3, y: 1 }, { x: 4, y: 1 }],
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1,
        durationMs: 1600,
        caption: "Yellow tiles are walkable floor.",
      },
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }],
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1,
        durationMs: 1400,
        caption: "Stone blocks are solid walls.",
      },
      {
        characterAt: { x: 2, y: 1 },
        fingerAt: { x: 2, y: 1 },
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.6,
        durationMs: 500,
        sound: "tap",
      },
      {
        characterAt: { x: 3, y: 1 },
        fingerAt: { x: 3, y: 1 },
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.6,
        durationMs: 450,
        sound: "tap",
      },
      {
        characterAt: { x: 4, y: 1 },
        fingerAt: { x: 4, y: 1 },
        cameraFocus: { x: 4, y: 1 },
        cameraZoom: 1.6,
        durationMs: 450,
        sound: "tap",
      },
      {
        characterAt: { x: 5, y: 1 },
        highlightCells: [{ x: 5, y: 1 }],
        cameraFocus: { x: 5, y: 1 },
        cameraZoom: 1.6,
        durationMs: 1200,
        sound: "chime",
        caption: "Reach the ladder to clear the level!",
      },
      {
        uiCallout: { icon: "restart", label: "Replay" },
        durationMs: 2800,
        caption: "Heads up: some moves can leave you stuck with no way to finish — the game won't warn you. Remember this ↻ Replay button — it restarts the level instantly, no penalty.",
      },
    ],
  },
  {
    id: "arrow-single",
    title: "Arrow Tile",
    text: "Once you step onto an arrow, you'll keep gliding that direction until something stops you. You can also tap an arrow from a distance to grab and slide it elsewhere.",
    triggerCellTypes: [7, 8, 9, 10],
    miniGrid: [
      [2, 2, 2, 2, 2, 2],
      [2, 0, 8, 5, 5, 2],
      [2, 2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.2,
        durationMs: 1500,
        caption: "This arrow points right.",
      },
      {
        characterAt: { x: 2, y: 1 },
        fingerAt: { x: 2, y: 1 },
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.4,
        durationMs: 500,
        sound: "tap",
      },
      {
        characterAt: { x: 4, y: 1 },
        highlightCells: [{ x: 3, y: 1 }, { x: 4, y: 1 }],
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.4,
        durationMs: 1300,
        slowMotion: true,
        sound: "glide",
        caption: "...until something stops you.",
      },
      {
        characterAt: { x: 1, y: 1 },
        fingerAt: { x: 2, y: 1 },
        arrowAt: { x: 2, y: 1 },
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.4,
        durationMs: 900,
        slowMotion: true,
        sound: "tap",
        caption: "Step off — tap an arrow from anywhere to grab it.",
      },
      {
        characterAt: { x: 1, y: 1 },
        fingerAt: { x: 5, y: 1 },
        arrowAt: { x: 4, y: 1 },
        highlightCells: [{ x: 3, y: 1 }, { x: 4, y: 1 }],
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.3,
        durationMs: 1000,
        slowMotion: true,
        sound: "glide",
        caption: "Choose a direction and it glides on, just like you.",
      },
    ],
  },
  {
    id: "arrow-multi",
    title: "Multi-Directional Arrow",
    text: "Multi-way arrows glide wherever you press — the same tile can send you several directions. They can be grabbed and slid from a distance, too.",
    triggerCellTypes: [11, 12, 13],
    miniGrid: [
      [2, 2, 2, 0, 2, 2, 2],
      [2, 5, 5, 13, 5, 5, 2],
      [2, 2, 2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 3, y: 0 },
        highlightCells: [{ x: 3, y: 1 }],
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.1,
        durationMs: 1300,
        caption: "This arrow opens in every direction.",
      },
      {
        characterAt: { x: 3, y: 1 },
        fingerAt: { x: 3, y: 1 },
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.3,
        durationMs: 450,
        sound: "tap",
      },
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 1, y: 1 }, { x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.3,
        durationMs: 1000,
        slowMotion: true,
        sound: "glide",
        caption: "Press left...",
      },
      {
        characterAt: { x: 3, y: 1 },
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.3,
        durationMs: 350,
        sound: "tap",
      },
      {
        characterAt: { x: 5, y: 1 },
        highlightCells: [{ x: 4, y: 1 }, { x: 5, y: 1 }],
        cameraFocus: { x: 4, y: 1 },
        cameraZoom: 1.3,
        durationMs: 1000,
        slowMotion: true,
        sound: "glide",
        caption: "...or press right. You choose.",
      },
      {
        characterAt: { x: 3, y: 0 },
        fingerAt: { x: 3, y: 1 },
        arrowAt: { x: 3, y: 1 },
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.3,
        durationMs: 900,
        slowMotion: true,
        sound: "tap",
        caption: "Step off — tap the arrow from anywhere to grab it.",
      },
      {
        characterAt: { x: 3, y: 0 },
        fingerAt: { x: 0, y: 1 },
        arrowAt: { x: 1, y: 1 },
        highlightCells: [{ x: 2, y: 1 }, { x: 1, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.3,
        durationMs: 1000,
        slowMotion: true,
        sound: "glide",
        caption: "It glides whichever way you choose.",
      },
    ],
  },
  {
    // Shown once, forced at level 2 regardless of cell types present (see the currentLevel.id
    // === 2 check in PuzzleGame.tsx) rather than the usual triggerCellTypes detection — this is
    // the level where an arrow first sits somewhere the player physically can't walk to, so
    // remote control stops being optional trivia and becomes the way to solve the puzzle.
    id: "arrow-remote",
    title: "Remote Arrow Control",
    text: "You don't have to stand next to an arrow to move it. Tap it from anywhere, then use your movement controls to walk it into place — even across a gap you could never cross yourself.",
    triggerCellTypes: [11, 12, 13],
    miniGrid: [
      [2, 2, 2, 2, 2, 2, 2],
      [2, 0, 0, 5, 13, 0, 2],
      [2, 2, 2, 5, 0, 3, 2],
      [2, 2, 2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 4, y: 1 }],
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1,
        durationMs: 1400,
        caption: "This arrow is stuck behind a gap — there's no path to it.",
      },
      {
        characterAt: { x: 1, y: 1 },
        fingerAt: { x: 4, y: 1 },
        cameraFocus: { x: 4, y: 1 },
        cameraZoom: 1.3,
        durationMs: 600,
        sound: "tap",
        caption: "Tap it anyway — distance doesn't matter.",
      },
      {
        characterAt: { x: 1, y: 1 },
        fingerAt: { x: 4, y: 2 },
        arrowAt: { x: 4, y: 2 },
        highlightCells: [{ x: 4, y: 1 }, { x: 4, y: 2 }],
        cameraFocus: { x: 4, y: 1.5 },
        cameraZoom: 1.2,
        durationMs: 900,
        slowMotion: true,
        sound: "glide",
        caption: "Your movement controls slide it now — not you.",
      },
      {
        characterAt: { x: 1, y: 1 },
        fingerAt: { x: 5, y: 2 },
        arrowAt: { x: 5, y: 2 },
        highlightCells: [{ x: 4, y: 2 }, { x: 5, y: 2 }],
        cameraFocus: { x: 4.5, y: 2 },
        cameraZoom: 1.2,
        durationMs: 900,
        slowMotion: true,
        sound: "glide",
        caption: "Keep going, one hop at a time, until it's in place.",
      },
    ],
  },
  {
    id: "breakable-rock",
    title: "Breakable Rock",
    text: "Step into a cracked rock to smash through it — it stays open after.",
    triggerCellTypes: [6],
    miniGrid: [
      [2, 2, 2, 2, 2],
      [2, 0, 6, 0, 2],
      [2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.4,
        durationMs: 1300,
        caption: "This rock is cracked — it'll give way.",
      },
      {
        characterAt: { x: 2, y: 1 },
        fingerAt: { x: 2, y: 1 },
        highlightCells: [{ x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.5,
        durationMs: 700,
        sound: "break",
        caption: "One step smashes it open.",
      },
      {
        characterAt: { x: 3, y: 1 },
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.2,
        durationMs: 500,
      },
    ],
  },
  {
    id: "key-lock",
    title: "Keys & Locks",
    text: "Collect a key to unlock the matching lock — you'll need it to pass.",
    triggerCellTypes: [14, 15, 16, 17],
    miniGrid: [
      [2, 2, 2, 2, 2, 2, 2],
      [2, 0, 14, 0, 16, 0, 2],
      [2, 2, 2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.3,
        durationMs: 1300,
        caption: "Grab the key.",
      },
      {
        characterAt: { x: 2, y: 1 },
        fingerAt: { x: 2, y: 1 },
        highlightCells: [{ x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.3,
        durationMs: 600,
        sound: "collect",
      },
      {
        characterAt: { x: 3, y: 1 },
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.3,
        durationMs: 400,
        sound: "tap",
      },
      {
        characterAt: { x: 4, y: 1 },
        highlightCells: [{ x: 4, y: 1 }],
        cameraFocus: { x: 4, y: 1 },
        cameraZoom: 1.3,
        durationMs: 900,
        sound: "unlock",
        caption: "The matching lock opens.",
      },
      {
        characterAt: { x: 5, y: 1 },
        cameraFocus: { x: 4, y: 1 },
        cameraZoom: 1.1,
        durationMs: 500,
      },
    ],
  },
  {
    id: "teleport",
    title: "Teleport",
    text: "Step onto a teleport pad to instantly travel to its matching pad.",
    triggerCellTypes: [19],
    miniGrid: [
      [2, 2, 2, 2, 2, 2, 2, 2],
      [2, 0, 19, 0, 0, 19, 0, 2],
      [2, 2, 2, 2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 2, y: 1 }, { x: 5, y: 1 }],
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1,
        durationMs: 1500,
        caption: "These two pads are linked.",
      },
      {
        characterAt: { x: 2, y: 1 },
        fingerAt: { x: 2, y: 1 },
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.5,
        durationMs: 500,
        sound: "tap",
      },
      {
        characterAt: { x: 5, y: 1 },
        highlightCells: [{ x: 5, y: 1 }],
        cameraFocus: { x: 5, y: 1 },
        cameraZoom: 1.5,
        durationMs: 900,
        sound: "teleport",
        caption: "Instant travel to the matching pad!",
      },
      {
        characterAt: { x: 6, y: 1 },
        cameraFocus: { x: 5, y: 1 },
        cameraZoom: 1.2,
        durationMs: 500,
      },
    ],
  },
  {
    id: "bonus-time",
    title: "Bonus Time",
    text: "Collect the hourglass to add extra seconds to the level's countdown timer.",
    triggerCellTypes: [20],
    miniGrid: [
      [2, 2, 2, 2, 2],
      [2, 0, 20, 0, 2],
      [2, 2, 2, 2, 2],
    ],
    steps: [
      {
        characterAt: { x: 1, y: 1 },
        highlightCells: [{ x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.4,
        durationMs: 1300,
        caption: "An hourglass — free time on the clock.",
      },
      {
        characterAt: { x: 2, y: 1 },
        fingerAt: { x: 2, y: 1 },
        highlightCells: [{ x: 2, y: 1 }],
        cameraFocus: { x: 2, y: 1 },
        cameraZoom: 1.5,
        durationMs: 800,
        sound: "collect",
        caption: "+ time added instantly.",
      },
      {
        characterAt: { x: 3, y: 1 },
        cameraFocus: { x: 3, y: 1 },
        cameraZoom: 1.2,
        durationMs: 500,
      },
    ],
  },
];

export const getTutorialDefinition = (id: string) => TUTORIAL_DEFINITIONS.find((t) => t.id === id) ?? null;
